networks:
  app_net:
    external: true
    name: app_net
  web_net:
    external: true
    name: web_net

services:
  cadvisor:
    image: docker.io/ahmadrafiee/cadvisor
    command: --disable_metrics=disk,udp,percpu
    restart: ${RESTART_POLICY}
    hostname: '${HOSTNAME}'
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    # ports:
    # - 8080:8080
    networks:
    - app_net
    - web_net
 
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.cadvisor.entrypoints=http
      - traefik.http.routers.cadvisor.rule=Host(`${CADSUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.cadvisor.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.cadvisor-secure.entrypoints=https
      - traefik.http.routers.cadvisor-secure.rule=Host(`${CADSUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.cadvisor-secure.tls=true
      - traefik.http.routers.cadvisor-secure.tls.options=default
      - traefik.http.routers.cadvisor-secure.middlewares=web-auth
      - traefik.http.routers.cadvisor-secure.tls.certresolver=mycert
      - traefik.http.services.cadvisor.loadbalancer.server.port=8080
  node-exporter:
    image: prom/node-exporter:v1.9.1
    restart: ${RESTART_POLICY}
    hostname: '${HOSTNAME}'
    container_name: node-exporter
    # network_mode: host ##
    pid: host ##
    volumes:
      - /:/host:ro,rslave
    command:
      - --path.rootfs=/host # tell node-exporter to read from /host
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|host/var/lib/docker/containers|host/var/lib/docker/overlay2|host/run/docker/netns|host/var/lib/docker/aufs)($$|/)"
  
    networks:
    - app_net
    - web_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.node.entrypoints=http
      - traefik.http.routers.node.rule=Host(`${NODESUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.node.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.node-secure.entrypoints=https
      - traefik.http.routers.node-secure.rule=Host(`${NODESUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.node-secure.tls=true
      - traefik.http.routers.node-secure.tls.options=default
      - traefik.http.routers.node-secure.middlewares=web-auth
      - traefik.http.routers.node-secure.tls.certresolver=mycert
      - traefik.http.services.node.loadbalancer.server.port=9100
    # ports:
    #   - 9100:9100
  promtail:
    image: grafana/promtail:3.5
    restart: ${RESTART_POLICY}
    container_name: promtail
    volumes:
    - /var/log:/var/log
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - ./promtail:/etc/promtail/
    command: -config.file=/etc/promtail/promtail.yml
    networks:
    - app_net
    - web_net